//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSPecor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEOB_ESTADO
    {
        public GEOB_ESTADO()
        {
            this.GEOB_CARROUSEL = new HashSet<GEOB_CARROUSEL>();
            this.GEOB_ENLACES_PANEL = new HashSet<GEOB_ENLACES_PANEL>();
            this.GEOB_GRUPOS = new HashSet<GEOB_GRUPOS>();
            this.GEOB_MAPAS_CATALOGO = new HashSet<GEOB_MAPAS_CATALOGO>();
            this.GEOB_PANEL = new HashSet<GEOB_PANEL>();
            this.GEOB_SERVICIOS_CATALOGO = new HashSet<GEOB_SERVICIOS_CATALOGO>();
            this.GEOB_TIPO_CATALOGO = new HashSet<GEOB_TIPO_CATALOGO>();
            this.GEOB_TIPO_SRV = new HashSet<GEOB_TIPO_SRV>();
            this.GEOB_TEMATICAS = new HashSet<GEOB_TEMATICAS>();
        }
    
        public decimal ID_ESTADO { get; set; }
        public string ESTADO { get; set; }
    
        public virtual ICollection<GEOB_CARROUSEL> GEOB_CARROUSEL { get; set; }
        public virtual ICollection<GEOB_ENLACES_PANEL> GEOB_ENLACES_PANEL { get; set; }
        public virtual ICollection<GEOB_GRUPOS> GEOB_GRUPOS { get; set; }
        public virtual ICollection<GEOB_MAPAS_CATALOGO> GEOB_MAPAS_CATALOGO { get; set; }
        public virtual ICollection<GEOB_PANEL> GEOB_PANEL { get; set; }
        public virtual ICollection<GEOB_SERVICIOS_CATALOGO> GEOB_SERVICIOS_CATALOGO { get; set; }
        public virtual ICollection<GEOB_TIPO_CATALOGO> GEOB_TIPO_CATALOGO { get; set; }
        public virtual ICollection<GEOB_TIPO_SRV> GEOB_TIPO_SRV { get; set; }
        public virtual ICollection<GEOB_TEMATICAS> GEOB_TEMATICAS { get; set; }
    }
}
