//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSPecor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEOB_TEMATICAS
    {
        public GEOB_TEMATICAS()
        {
            this.GEOB_GRUPOS = new HashSet<GEOB_GRUPOS>();
            this.GEOB_MAPAS_CATALOGO = new HashSet<GEOB_MAPAS_CATALOGO>();
        }
    
        public decimal ID_TEMATICA { get; set; }
        public string NOMBRE { get; set; }
        public string URL_IMG { get; set; }
        public Nullable<decimal> FK_ID_ESTADO { get; set; }
        public Nullable<decimal> FK_ID_USUARIO { get; set; }
        public Nullable<System.DateTime> FECHA_REGISTRO { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual GEOB_ESTADO GEOB_ESTADO { get; set; }
        public virtual ICollection<GEOB_GRUPOS> GEOB_GRUPOS { get; set; }
        public virtual ICollection<GEOB_MAPAS_CATALOGO> GEOB_MAPAS_CATALOGO { get; set; }
    }
}
